image: python:3-alpine

before_script:
  - apk update
  - apk add zip

stages:
  - test
  - build

test:
  stage: test
  script:
    - python -mjson.tool 'fr.json' > /dev/null
    - python -mjson.tool 'module.json' > /dev/null

build:
  stage: build
  script:
    - zip wh4-fr-FR.zip -r *.js *.json *.md compendium lang tables -x ".*"
  artifacts:
    name: wh4-fr-FR
    when: on_success
    paths:
      - wh4-fr-FR.zip
  when: on_success
  only:
    - tags
    - master
